- hosts: Wedding
  
  tasks:
    - name: update apt cache 
      apt: update_cache=yes cache_valid_time=3600  

    - name: Create required directories
      file: path='/srv/www/wedding/media/' state=directory    
      

  roles:
    - Ansibles.build-essential
    - Ansibles.python
    - Ansibles.nginx
    - Ansibles.postgresql
    - toast38coza.djangoapp

  vars:
    postgresql_databases:
      - name: tam

    postgresql_users:
      - name: tam
        pass: tam
        encrypted: no       # denotes if the password is already encrypted.

    postgresql_user_privileges:
      - name: tam          # user name
        db: tam            # database
        priv: "ALL"        # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL

    ## notes: path_to_requirements, path_to_managepy: unless blank, must have trailing slash
    django_apps: 
      - {
        "djangoapp_projectname" : "wedding", 
        "djangoapp_track_branch": "master", 
        "djangoapp_repo" : "git@github.com:toast38coza/WeddingSite.git", 
        "path_to_requirements" : "", 
        "path_to_managepy" : "",
        "djangoapp_httpport": 8001,
        "djangoapp_domains" : "tammyandmichael.us www.tammyandmichael.us",
        "djangoapp_pythonversion" : "2.7",
        "djangoapp_db_engine" : "postgresql_psycopg2",
        "djangoapp_db_host" : "127.0.0.1" }

